name: foodsafe
description: FoodSafe app with profile photo feature in drawer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  path_provider: ^2.1.5
  flutter_image_compress: ^2.4.0
  image_picker: ^1.2.0
  path: ^1.8.3
  provider: ^6.0.5
  cross_file: ^0.3.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.5.1
  build_runner: ^2.10.0

flutter:
  uses-material-design: true